/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uploads;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ksa
 */
public class TelaUp extends javax.swing.JFrame {

    File arq;

    /**
     * Creates new form TelaUp
     */
    public TelaUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnBaixar = new javax.swing.JButton();
        txtBaixar = new javax.swing.JTextField();
        txtEnviar = new javax.swing.JLabel();
        selAquivo = new javax.swing.JButton();
        txtProcurar = new javax.swing.JTextField();
        txtEnviar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtbusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnviar.setText("Enviar");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEnviarMousePressed(evt);
            }
        });
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBaixar.setText("Baixar");

        txtBaixar.setText("Baixar Arquivos");

        txtEnviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEnviar.setText("Selecionar Arquivo");

        selAquivo.setText("Procurar...");
        selAquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selAquivoActionPerformed(evt);
            }
        });

        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });

        txtEnviar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEnviar1.setText("Arquivos Diretorio");

        txtbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selAquivo)
                                .addGap(34, 34, 34)
                                .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEnviar)
                            .addComponent(txtEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar))
                                .addGap(159, 159, 159)
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnBaixar)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(txtEnviar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selAquivo)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnviar1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaixar)
                    .addComponent(txtBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:

//        System.out.println("Entrou ak");
////        String caminho = getClass().getResource("../imagens/").toString().substring(10);
//        String caminho = ("C:\\Users\\Ksa\\Documents\\NetBeansProjects\\uploadJava\\Upload\\build\\classes\\imegens");
//        
//        //File outputfile = new File(caminho);
//        
//        System.out.println("Caminho " + caminho);
//        //String nameArquivo = outputfile.getName();
//
//       // System.out.println("Entrou 2 " + nameArquivo);
//        System.out.println("Nome do Arquivo: " + arq.getName());
//        System.out.println("Caminho Salvar: " + caminho);
        //      File arquivo = new File(caminho + arq.getName());
//        try {
//            arquivo.createNewFile();
//            System.out.println("Arquivo criado");
//            //arquivo
//        } catch (IOException ex) {
//            Logger.getLogger(TelaUp.class.getName()).log(Level.SEVERE, null, ex);
//        }
        //Verificar pq esta criando local
//        try {
//            
//            System.out.println("Entrou no try");
//            outputfile.createNewFile();
//        } catch (IOException ex) {
//            Logger.getLogger(TelaUp.class.getName()).log(Level.SEVERE, null, ex);
//        }
        try {
            Socket socketNo1 = new Socket("127.0.0.1", 4001);
            System.out.println("O cliente se conectou ao servidorNo1!");

            Socket socketNo2 = new Socket("127.0.0.1", 4002);
            System.out.println("O cliente se conectou ao servidorNo2!");

            Socket socketNo3 = new Socket("127.0.0.1", 4003);
            System.out.println("O cliente se conectou ao servidorNo3!");

            Socket socketNo4 = new Socket("127.0.0.1", 4004);
            System.out.println("O cliente se conectou ao servidorNo4!");

            long lenght = arq.length();
            if (lenght / 1024 > 4096) {
                System.out.println("Tamanho " + lenght);
                System.out.println("Arquivo muito grande1!");
            } else {
                System.out.println("Tamanho Aceitavel!");
                //showOpenDialog(this);

            }
            System.out.println(lenght);
            
            byte[] bytes = new byte[1024 * 1024];// 1MB
            InputStream in = new FileInputStream(arq);
            OutputStream out1 = socketNo1.getOutputStream();
            OutputStream out2 = socketNo2.getOutputStream();
            OutputStream out3 = socketNo3.getOutputStream();
            OutputStream out4 = socketNo4.getOutputStream();
            int partCounter = 0;
            int count;

//            while ((count = in.read(bytes)) > 0) {;
//                out1.write(bytes, 0, count);
//                out2.write(bytes, 0, count);
//                out3.write(bytes, 0, count);
//                out4.write(bytes, 0, count);
//
//            }
            OutputStream[] outs;
            outs = new OutputStream[5];
            outs[0] = out1;
            outs[1] = out2;
            outs[2] = out3;
            outs[3] = out4;

            System.out.println(outs[0]);
            String fileName = arq.getName();
            System.out.println("filename");
            System.out.println(fileName);
            
            try (FileInputStream fis = new FileInputStream(arq);
                    BufferedInputStream bis = new BufferedInputStream(fis)) {

                int bytesAmount = 0;
                while ((bytesAmount = bis.read(bytes)) > 0) {
                    //write each chunk of data into separate file with different number in name
                    String filePartName = String.format("%s.%03d", fileName, partCounter++);
                    File newFile = new File(arq.getParent(), filePartName);
                    try (FileOutputStream out = new FileOutputStream(newFile)) {
                        System.out.println(partCounter);
                        //manda cada parte de 1mb para os servidores, se o arquivo for menor que 1, manda só para o primeiro
                        outs[partCounter - 1].write(bytes, 0, bytesAmount);
                        //splita o arquivo e grava no mesmo local em partes
                        out.write(bytes, 0, bytesAmount);
                    }
                }
            }

            out1.close();
            out2.close();
            out3.close();
            out4.close();
            in.close();
            socketNo1.close();
            socketNo2.close();
            socketNo3.close();
            socketNo4.close();

        } catch (IOException ex) {
            Logger.getLogger(TelaUp.class.getName()).log(Level.SEVERE, null, ex);
        }

        // JOptionPane.showMessageDialog(rootPane, "Imagem enviada com sucesso");

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void selAquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selAquivoActionPerformed
        // TODO add your handling code here:
        
        
        JFileChooser selArquivo = new JFileChooser();
        int res = selArquivo.showOpenDialog(null);
        
        if (res == JFileChooser.APPROVE_OPTION) {
            //selArquivo.getMaximumSize(4096)
//            if (selArquivo.getMaximumSize(4096)< 4096){
//            } else {
//                
//            }
           
            JOptionPane.showMessageDialog(null, "Selecionado com Sucesso.");

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
        File arquivo = selArquivo.getSelectedFile();
        arq = arquivo;
        txtProcurar.setText(arquivo.getPath()); // coloca caminho do arquivo.
        System.out.println("TESTE: " + arquivo.getName());

    }//GEN-LAST:event_selAquivoActionPerformed

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtProcurarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        Socket socketNo1 = null;
        Socket socketNo2 = null;
        Socket socketNo3 = null;
        Socket socketNo4 = null;
        
        
        try {
            socketNo1 = new Socket("127.0.0.1", 4001);
            System.out.println("O cliente se conectou ao servidorNo1!");
            socketNo2 = new Socket("127.0.0.1", 4002);
            System.out.println("O cliente se conectou ao servidorNo2!");
            socketNo3 = new Socket("127.0.0.1", 4003);
            System.out.println("O cliente se conectou ao servidorNo3!");
            socketNo4 = new Socket("127.0.0.1", 4004);
            System.out.println("O cliente se conectou ao servidorNo4!");
        } catch (IOException ex) {
            Logger.getLogger(TelaUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //System.out.println("O cliente se conectou ao servidorNo1!");
        byte[] bytes = new byte[1024 * 4096];
        try {
            OutputStream out = null;
            out = new FileOutputStream("C:\\Users\\igor.amaral\\Documents\\NetBeansProjects\\arquivos\\novo.png");
            
            //BufferedReader FromServer = new BufferedReader (new InputStreamReader(socketNo1.getInputStream()));
            //DataOutputStream OutToClient = new DataOutputStream(soc_1.getOutputStream());            
            //final DataInputStream InFromClient = new DataInputStream(socketNo1.getInputStream());
            //final DataOutputStream ToServer = new DataOutputStream(socketNo1.getOutputStream());                    
            final DataInputStream FromServer1 = new DataInputStream(socketNo1.getInputStream());
            final DataOutputStream ToServer1 = new DataOutputStream(socketNo1.getOutputStream());            
            final DataInputStream FromServer2 = new DataInputStream(socketNo2.getInputStream());
            final DataOutputStream ToServer2 = new DataOutputStream(socketNo2.getOutputStream());                                
            final DataInputStream FromServer3 = new DataInputStream(socketNo3.getInputStream());
            final DataOutputStream ToServer3 = new DataOutputStream(socketNo3.getOutputStream());                                
            final DataInputStream FromServer4 = new DataInputStream(socketNo4.getInputStream());
            final DataOutputStream ToServer4 = new DataOutputStream(socketNo4.getOutputStream());                                
            ToServer1.writeInt(1);
            ToServer2.writeInt(1);
            ToServer3.writeInt(1);
            ToServer4.writeInt(1);
            
            OutputStream out1 = socketNo1.getOutputStream();
            
            int count;
            while ((count = FromServer1.read(bytes)) > 0) {
                out.write(bytes, 0, count);
            }
            while ((count = FromServer2.read(bytes)) > 0) {
                out.write(bytes, 0, count);
            }
            while ((count = FromServer3.read(bytes)) > 0) {
                out.write(bytes, 0, count);
            }
            while ((count = FromServer4.read(bytes)) > 0) {
                out.write(bytes, 0, count);
            }            
            out.close();

        } catch (Exception E ) {System.out.println(E);}

        
//        
//        FileInputStream fis1 = new FileInputStream(busca1);
//        BufferedInputStream bis1 = new BufferedInputStream(fis1);
////        String caminho = getClass().getResource("../imagens/").toString().substring(5);
//        String caminho = ("C:\\Users\\Ksa\\Documents\\NetBeansProjects\\uploadJava\\Upload\\src\\imegens\\");
//
//        File busca = new File(caminho);
//        String listaD = "";
//        String[] list = busca.list();
//        for (String arquivos : list) {
//
//            //System.out.println(arquivos);
//            //System.out.print("lisfiles"+busca.listFiles() );
//            int i;
//            //System.out.print("teste chritian "+ busca.getParent());
//
//            listaD += arquivos + "\r\n";
//
//            //int qnt = busca.listFiles().length;
//            for (i = 0; i <= busca.listFiles().length; i++) {
//
//                //System.out.println(arquivos);
//            }
//
//        }
//        txtbusca.setText(listaD);
//        System.out.println("listaD" + listaD);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscaActionPerformed
//       String caminho = getClass().getResource("../imagens/").toString().substring(5);
//        
//        File file = new File(caminho);
//        System.out.println("Caminho "+ caminho);
//       File[] arquivos = file.listFiles();
//
//       for (File fileTmp : arquivos) {
//     System.out.println("da net "+fileTmp.getName());
//     
//   
//   }

// TODO add your handling code here:
    }//GEN-LAST:event_txtbuscaActionPerformed

    private void btnEnviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaixar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton selAquivo;
    private javax.swing.JTextField txtBaixar;
    private javax.swing.JLabel txtEnviar;
    private javax.swing.JLabel txtEnviar1;
    private javax.swing.JTextField txtProcurar;
    private javax.swing.JTextField txtbusca;
    // End of variables declaration//GEN-END:variables
}
